# -*- coding: utf-8 -*-
"""KSOFM_A2_Clustering Patients Based on Lifestyle and Health Habits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcAbblgzJygaVnQppH9_7uMzWXGOBK7i
"""

import numpy as np
import pandas as pd

# -----------------------------------------
# 1. Sample Dataset
# -----------------------------------------
data = {
    "Patient": ["P1", "P2", "P3", "P4", "P5", "P6"],
    "BMI": [22, 28, 31, 24, 20, 27],
    "Exercise": [45, 15, 10, 60, 30, 20],
    "Sugar": [30, 60, 80, 55, 20, 70],
    "Smoking": [0, 5, 10, 0, 0, 7],
    "Alcohol": [2, 8, 12, 5, 1, 9]
}

df = pd.DataFrame(data)

# Features for SOFM
X = df.iloc[:, 1:].values

# Normalize inputs
X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

# -----------------------------------------
# 2. SOFM Configuration
# -----------------------------------------
input_dim = X.shape[1]     # 5 input features
output_neurons = 4         # 4 clusters
learning_rate = 0.5
epochs = 100

np.random.seed(42)

# Random weight initialization
weights = np.random.rand(output_neurons, input_dim)

# -----------------------------------------
# 3. Train SOFM
# -----------------------------------------
for epoch in range(epochs):
    for sample in X:
        # Distance between input sample and each neuron
        distances = np.linalg.norm(weights - sample, axis=1)

        # Best Matching Unit (BMU)
        bmu_index = np.argmin(distances)

        # Update BMU weights
        weights[bmu_index] += learning_rate * (sample - weights[bmu_index])

    learning_rate *= 0.98  # decay

# -----------------------------------------
# 4. Assign clusters to patients
# -----------------------------------------
cluster_assignments = []

for sample in X:
    distances = np.linalg.norm(weights - sample, axis=1)
    bmu_index = np.argmin(distances)
    cluster_assignments.append(bmu_index)

df["Cluster"] = cluster_assignments

print("\nFinal Patient Cluster Assignments:")
print(df)