# -*- coding: utf-8 -*-
"""KSOFM_B2_Clustering CSE Students Based on Academic and Skill Profiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXMw3G2dS48TQZ4oh4jPlC6J0pgf_xe5
"""

# pip install minisom

import numpy as np
from minisom import MiniSom
from sklearn.preprocessing import MinMaxScaler

# ---------------------------
# 1. INPUT DATA
# ---------------------------
data = np.array([
    [9.2, 95, 5, 6, 8],    # S1
    [7.5, 80, 3, 4, 5],    # S2
    [6.0, 55, 1, 0, 4],    # S3
    [8.0, 70, 2, 3, 9],    # S4
    [5.8, 50, 1, 1, 6],    # S5
    [7.0, 65, 4, 5, 7]     # S6
])

student_ids = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6']

# ---------------------------
# 2. NORMALIZATION
# ---------------------------
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

# ---------------------------
# 3. INITIALIZE SOM (2x2 grid → 4 clusters)
# ---------------------------
som = MiniSom(
    x=2, y=2,
    input_len=5,
    sigma=1.0,
    learning_rate=0.5,
    random_seed=42
)

som.random_weights_init(data_scaled)

# ---------------------------
# 4. TRAIN SOM
# ---------------------------
som.train_random(data_scaled, 200)

# ---------------------------
# 5. ASSIGN CLUSTERS
# ---------------------------
cluster_assignments = []
for sample in data_scaled:
    winner = som.winner(sample)
    cluster_num = winner[0] * 2 + winner[1]   # 2x2 → convert to 4 labels
    cluster_assignments.append(cluster_num)

# ---------------------------
# 6. DISPLAY RESULTS
# ---------------------------
print("\nFinal Cluster Assignments:")
for sid, cluster in zip(student_ids, cluster_assignments):
    print(f"{sid} → Cluster {cluster}")