# -*- coding: utf-8 -*-
"""KSOFM_B1_Clustering Countries Based on Renewable Energy Adoption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rL6N-R37Tnk-POnmrfbjSGp0fB6EqM_O
"""

import numpy as np
import pandas as pd

# -----------------------------------------
# 1. Sample Dataset
# -----------------------------------------
data = {
    "Country": ["C1", "C2", "C3", "C4", "C5", "C6"],
    "Renewable%": [55, 20, 10, 75, 25, 65],
    "Emissions": [3.2, 9.0, 12.5, 1.5, 8.0, 2.0],
    "GDP": [45000, 30000, 15000, 50000, 20000, 48000],
    "Efficiency": [85, 70, 40, 90, 60, 88],
    "Population": [10, 50, 80, 5, 40, 8]
}

df = pd.DataFrame(data)

# Features for SOFM
X = df.iloc[:, 1:].values

# Normalize inputs (important for SOFM)
X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

# -----------------------------------------
# 2. SOFM Configuration
# -----------------------------------------
input_dim = X.shape[1]            # 5 features
output_neurons = 4                # 4 clusters
learning_rate = 0.5
epochs = 100

# Initialize weights randomly
np.random.seed(42)
weights = np.random.rand(output_neurons, input_dim)

# -----------------------------------------
# 3. Train Kohonen SOFM
# -----------------------------------------
for epoch in range(epochs):
    for sample in X:
        # Calculate distance from sample to each neuron
        distances = np.linalg.norm(weights - sample, axis=1)

        # Winner neuron = Best Matching Unit (BMU)
        bmu_index = np.argmin(distances)

        # Update BMU weights
        weights[bmu_index] += learning_rate * (sample - weights[bmu_index])

    # Slowly decrease learning rate
    learning_rate *= 0.98

# -----------------------------------------
# 4. Assigning clusters
# -----------------------------------------
cluster_assignments = []
for sample in X:
    distances = np.linalg.norm(weights - sample, axis=1)
    bmu_index = np.argmin(distances)
    cluster_assignments.append(bmu_index)

df["Cluster"] = cluster_assignments

print("\nFinal Cluster Assignments:")
print(df)