# -*- coding: utf-8 -*-
"""KSOFM_B1_Clustering Areas Based on Air Pollution and Health Impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRB8JH88b0i71-YQiKrleciN8xGH5SL2
"""

# pip install minisom

import numpy as np
from minisom import MiniSom
from sklearn.preprocessing import MinMaxScaler

# ---------------------------
# 1. INPUT DATA
# ---------------------------
data = np.array([
    [85, 75, 10, 90, 1500],   # A1
    [50, 40, 25, 60, 1200],   # A2
    [15, 10, 60, 20, 300],    # A3
    [20, 15, 40, 15, 3500],   # A4
    [60, 55, 20, 70, 1000],   # A5
    [18, 12, 45, 25, 4000]    # A6
])

area_names = ['A1', 'A2', 'A3', 'A4', 'A5', 'A6']

# ---------------------------
# 2. NORMALIZATION
# ---------------------------
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

# ---------------------------
# 3. INITIALIZE SOM (2x2 Grid = 4 Clusters)
# ---------------------------
som = MiniSom(
    x=2, y=2,          # 4 clusters total
    input_len=5,       # 5 features
    sigma=1.0,
    learning_rate=0.5,
    random_seed=42
)

som.random_weights_init(data_scaled)

# ---------------------------
# 4. TRAIN THE SOM
# ---------------------------
som.train_random(data_scaled, 200)   # 200 iterations

# ---------------------------
# 5. ASSIGN CLUSTERS
# ---------------------------
cluster_assignments = []
for i, sample in enumerate(data_scaled):
    winner = som.winner(sample)     # BMU → (x, y) position
    cluster_num = winner[0] * 2 + winner[1]   # Convert 2D → 1D cluster ID
    cluster_assignments.append(cluster_num)

# ---------------------------
# 6. OUTPUT RESULT
# ---------------------------
print("Final SOM Cluster Assignments:")
for name, cluster in zip(area_names, cluster_assignments):
    print(f"{name} → Cluster {cluster}")