# -*- coding: utf-8 -*-
"""LVQ_B4_ Classifying Individuals Based on Mental Health Profiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zogtLvLeTjAMTBcXk-i5plsmqeUUqWi4
"""

import numpy as np
from sklearn.preprocessing import MinMaxScaler

# -------------------------------------------
# 1. DATASET
# -------------------------------------------
X = np.array([
    [3, 8, 3, 6, 6],   # P1 - C1
    [7, 5, 4, 2, 10],  # P2 - C2
    [5, 6, 8, 1, 7],   # P3 - C3
    [8, 4, 6, 1, 11],  # P4 - C4
    [4, 7, 5, 5, 7],   # P5 - C1
    [9, 3, 7, 0, 12],  # P6 - C4
])

y = np.array([
    [1,0,0,0],   # C1
    [0,1,0,0],   # C2
    [0,0,1,0],   # C3
    [0,0,0,1],   # C4
    [1,0,0,0],   # C1
    [0,0,0,1],   # C4
])

ids = ["P1", "P2", "P3", "P4", "P5", "P6"]

# -------------------------------------------
# 2. NORMALIZATION
# -------------------------------------------
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# -------------------------------------------
# 3. INITIAL PROTOTYPES (1 PER CLASS)
# -------------------------------------------
# Select first instance of each class
W = np.array([
    X_scaled[0],  # C1
    X_scaled[1],  # C2
    X_scaled[2],  # C3
    X_scaled[3],  # C4
])

W_labels = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])

learning_rate = 0.3

# -------------------------------------------
# 4. LVQ TRAINING FUNCTION
# -------------------------------------------
def lvq_train(X, y, W, W_labels, lr, epochs=15):
    for ep in range(epochs):
        for i, sample in enumerate(X):
            label = y[i]

            # Calculate Euclidean distance
            distances = np.linalg.norm(W - sample, axis=1)
            winner = np.argmin(distances)

            # If correct class → move closer
            if np.array_equal(label, W_labels[winner]):
                W[winner] += lr * (sample - W[winner])
            else:
                # Wrong class → move away
                W[winner] -= lr * (sample - W[winner])

        lr *= 0.9   # decay

    return W

# -------------------------------------------
# 5. TRAIN LVQ
# -------------------------------------------
W_final = lvq_train(X_scaled, y, W.copy(), W_labels, learning_rate)

# -------------------------------------------
# 6. LVQ PREDICTION FUNCTION
# -------------------------------------------
def lvq_predict(sample, W, W_labels):
    distances = np.linalg.norm(W - sample, axis=1)
    winner = np.argmin(distances)
    return W_labels[winner]

# -------------------------------------------
# 7. PRINT RESULTS
# -------------------------------------------
print("\nLVQ Classification Results:")
for i, sample in enumerate(X_scaled):
    pred = lvq_predict(sample, W_final, W_labels)
    print(ids[i], "→ Predicted Class:", pred)