# -*- coding: utf-8 -*-
"""LVQ_A3_Classifying Students Based on Career Interests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YChSqPuzI_n6ue_jv7jPtNykDeZ235F
"""

import numpy as np
import pandas as pd

# ------------------------------------------------------
# 1. Dataset
# ------------------------------------------------------
data = {
    "Student": ["S1", "S2", "S3", "S4", "S5", "S6"],
    "GPA": [9.0, 8.0, 7.0, 6.5, 9.2, 8.5],
    "Prog": [95, 85, 70, 60, 90, 88],
    "Research": [8, 4, 5, 3, 9, 5],
    "Creativity": [6, 7, 5, 8, 4, 6],
    "Leadership": [7, 9, 6, 8, 5, 7],
    "Class": ["C1", "C3", "C4", "C3", "C1", "C2"]
}

df = pd.DataFrame(data)

X = df.iloc[:, 1:6].values
y = df["Class"].values

# ------------------------------------------------------
# 2. Normalize Features
# ------------------------------------------------------
X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

# Map class labels to integers
class_map = {"C1": 0, "C2": 1, "C3": 2, "C4": 3}
y_int = np.array([class_map[c] for c in y])

# ------------------------------------------------------
# 3. Initialize LVQ Prototypes (one per class)
# ------------------------------------------------------
num_classes = 4
input_dim = X.shape[1]

np.random.seed(42)
weights = np.random.rand(num_classes, input_dim)

learning_rate = 0.3
epochs = 50

# ------------------------------------------------------
# 4. LVQ Training
# ------------------------------------------------------
for epoch in range(epochs):
    for i in range(len(X)):
        sample = X[i]
        label = y_int[i]

        # Distance to all prototypes
        distances = np.linalg.norm(weights - sample, axis=1)
        winner = np.argmin(distances)

        # Update rule
        if winner == label:
            # Move prototype closer
            weights[winner] += learning_rate * (sample - weights[winner])
        else:
            # Move prototype away
            weights[winner] -= learning_rate * (sample - weights[winner])

    learning_rate *= 0.95  # decay

# ------------------------------------------------------
# 5. Final Classification
# ------------------------------------------------------
predicted = []
for sample in X:
    distances = np.linalg.norm(weights - sample, axis=1)
    winner = np.argmin(distances)
    predicted.append(winner)

df["Predicted_Class"] = predicted

# Reverse map
reverse_map = {0: "C1", 1: "C2", 2: "C3", 3: "C4"}
df["Predicted_Label"] = df["Predicted_Class"].map(reverse_map)

print("\nFinal LVQ Classification:")
print(df)