# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chJUIRu06hyKdAeHjcUKNrJ3ncPtXNtX
"""

# --------------------------------------------
# MP Neuron Model (Step Activation Function)
# --------------------------------------------

def mp_neuron(weights, inputs, threshold):
    total = sum(w * x for w, x in zip(weights, inputs))
    return 1 if total >= threshold else 0


# --------------------------------------------
# Basic logic using MP neurons
# --------------------------------------------

def AND(a, b):
    return mp_neuron([1, 1], [a, b], 2)

def OR(a, b):
    return mp_neuron([1, 1], [a, b], 1)

def NOT(a):
    return mp_neuron([-1], [a], 0)   # output = 1 if -a >= 0 → a = 0


# --------------------------------------------
# 2:1 Multiplexer ANN
# Y = S'·A + S·B
# --------------------------------------------

def mux_2to1(S, A, B):
    notS = NOT(S)

    term1 = AND(notS, A)  # S' A
    term2 = AND(S, B)     # S B

    Y = OR(term1, term2)  # final output
    return Y


# --------------------------------------------
# Test the MUX
# --------------------------------------------

print("S A B | Y")
print("-----------")
for S in [0, 1]:
    for A in [0, 1]:
        for B in [0, 1]:
            y = mux_2to1(S, A, B)
            print(S, A, B, "|", y)