# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chJUIRu06hyKdAeHjcUKNrJ3ncPtXNtX
"""

# ---------------------------------------------
# MP Neuron Model for Fruit Classification
# ---------------------------------------------

def fruit_classifier(shape, texture, weight):
    # Weights chosen logically based on features
    W_shape = 2       # Round → Apple
    W_texture = 1     # Smooth → Apple
    W_weight = 2      # Heavy → Apple

    bias = -2         # Can be modified

    # Weighted sum
    total = (W_shape * shape) + (W_texture * texture) + (W_weight * weight) + bias

    # Activation (Step Function)
    if total >= 0:
        return "Apple"
    else:
        return "Orange"


# ---------------------------------------------
# TEST CASES FOR THE CLASSIFIER
# ---------------------------------------------

samples = [
    ("Round, Smooth, Heavy", 1, 1, 1),
    ("Round, Rough, Heavy", 1, 0, 1),
    ("Elliptical, Smooth, Light", 0, 1, 0),
    ("Elliptical, Rough, Light", 0, 0, 0),
    ("Round, Smooth, Light", 1, 1, 0)
]

print("Fruit Classifier Results:")
print("--------------------------")

for desc, s, t, w in samples:
    result = fruit_classifier(s, t, w)
    print(f"{desc} → {result}")