# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chJUIRu06hyKdAeHjcUKNrJ3ncPtXNtX
"""

# -------------------------------------------
# MP Neuron Model (Step Activation Function)
# -------------------------------------------

def mp_neuron(weights, inputs, threshold):
    # Weighted sum
    total = sum(w * x for w, x in zip(weights, inputs))
    return 1 if total >= threshold else 0


# -------------------------------------------
# XOR neuron using 2 MP neurons (XOR = (A+B)-2AB)
# -------------------------------------------

def xor(a, b):
    # Neuron 1: OR gate
    or_output = mp_neuron([1, 1], [a, b], 1)

    # Neuron 2: AND gate
    and_output = mp_neuron([1, 1], [a, b], 2)

    # XOR = OR AND NOT(AND)
    return mp_neuron([1, -1], [or_output, and_output], 1)


# -------------------------------------------
# FULL ADDER USING MP NEURONS
# Sum = A XOR B XOR Cin
# Cout = majority(A, B, Cin)
# -------------------------------------------

def full_adder(a, b, cin):
    # Sum calculation using two XOR MP neurons
    xor1 = xor(a, b)
    sum_output = xor(xor1, cin)

    # Carry = majority function = (A&B) OR (B&Cin) OR (A&Cin)
    a_and_b = mp_neuron([1, 1], [a, b], 2)
    b_and_c = mp_neuron([1, 1], [b, cin], 2)
    a_and_c = mp_neuron([1, 1], [a, cin], 2)

    carry = mp_neuron([1, 1, 1], [a_and_b, b_and_c, a_and_c], 1)

    return sum_output, carry


# -------------------------------------------
# TEST THE FULL ADDER
# -------------------------------------------

print("A B Cin | Sum Carry")
print("--------------------")

for A in [0, 1]:
    for B in [0, 1]:
        for Cin in [0, 1]:
            s, c = full_adder(A, B, Cin)
            print(A, B, Cin, " | ", s, "   ", c)