# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chJUIRu06hyKdAeHjcUKNrJ3ncPtXNtX
"""

import numpy as np
import pandas as pd

# -----------------------------
# Garbage Sorting Dataset
# -----------------------------
data = {
    "Weight":   [15,20,35,40,18,25,30,50,22,28],
    "Moisture": [0.05,0.10,0.15,0.20,0.80,0.85,0.70,0.90,0.40,0.65],
    "Odor":     [0.0,0.1,0.0,0.05,0.9,0.8,0.7,0.95,0.3,0.6],
    "Texture":  [0,0,1,1,2,2,1,2,1,2],
    "Class":    [0,0,0,0,1,1,1,1,0,1]
}

df = pd.DataFrame(data)

# -----------------------------
# Normalize numeric features
# -----------------------------
def normalize(col):
    return (col - col.min()) / (col.max() - col.min())

df["Weight_n"] = normalize(df["Weight"])
df["Texture_n"] = normalize(df["Texture"])

# Final feature matrix
X = df[["Weight_n", "Moisture", "Odor", "Texture_n"]].values
y = df["Class"].values

# -----------------------------
# MP Neuron Parameters
# -----------------------------
# Weights chosen logically:
# Wet waste → Moist, bad odor, fibrous
W = np.array([0.4, 1.5, 1.4, 1.0])  # You can adjust
theta = 1.8  # Threshold

# -----------------------------
# MP Neuron Function
# -----------------------------
def mp_neuron(inputs, weights, threshold):
    total = np.dot(inputs, weights)
    return 1 if total >= threshold else 0

# -----------------------------
# Run predictions
# -----------------------------
predictions = []
for xi in X:
    predictions.append(mp_neuron(xi, W, theta))

df["Predicted"] = predictions

# Accuracy
accuracy = np.mean(df["Class"] == df["Predicted"]) * 100

print("\n=== MP Neuron Classification ===")
print(df[["Weight","Moisture","Odor","Texture","Class","Predicted"]])
print("\nAccuracy:", accuracy, "%")