# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chJUIRu06hyKdAeHjcUKNrJ3ncPtXNtX
"""

# -----------------------------------------
# MP Neuron for Rabbit vs Bear Classification
# -----------------------------------------

def classify_toy(ears_long, tail_short, body_heavy, climbs_trees):
    # Logical weights
    W_ears = -2        # Rabbit feature
    W_tail = -2        # Rabbit feature
    W_body = +3        # Bear feature
    W_climb = +3       # Bear feature
    bias = -1          # Adjustable

    total = (W_ears * ears_long +
             W_tail * tail_short +
             W_body * body_heavy +
             W_climb * climbs_trees +
             bias)

    if total >= 0:
        return 1  # Bear
    else:
        return 0  # Rabbit


# -----------------------------------------
# Testing on Given Dataset
# -----------------------------------------

dataset = [
    (1,1,0,0),
    (1,1,0,0),
    (1,1,0,1),
    (0,0,1,1),
    (0,0,1,0),
    (0,0,1,1)
]

print("Ears Tail Body Climb  =>  Class")
print("--------------------------------")

for row in dataset:
    result = classify_toy(*row)
    print(row, "=>", "Bear (1)" if result == 1 else "Rabbit (0)")